#GTM QUAD 209
set_property PACKAGE_PIN AE67 [get_ports {gt_rxp_in0[0]}]
set_property PACKAGE_PIN AE68 [get_ports {gt_rxn_in0[0]}]
set_property PACKAGE_PIN AG61 [get_ports {gt_txp_out0[0]}]
set_property PACKAGE_PIN AG62 [get_ports {gt_txn_out0[0]}]
set_property PACKAGE_PIN AE64 [get_ports {gt_rxp_in0[1]}]
set_property PACKAGE_PIN AE65 [get_ports {gt_rxn_in0[1]}]
set_property PACKAGE_PIN AG58 [get_ports {gt_txp_out0[1]}]
set_property PACKAGE_PIN AG59 [get_ports {gt_txn_out0[1]}]
set_property PACKAGE_PIN AC67 [get_ports {gt_rxp_in0[2]}]
set_property PACKAGE_PIN AC68 [get_ports {gt_rxn_in0[2]}]
set_property PACKAGE_PIN AE61 [get_ports {gt_txp_out0[2]}]
set_property PACKAGE_PIN AE62 [get_ports {gt_txn_out0[2]}]
set_property PACKAGE_PIN AC64 [get_ports {gt_rxp_in0[3]}]
set_property PACKAGE_PIN AC65 [get_ports {gt_rxn_in0[3]}]
set_property PACKAGE_PIN AE58 [get_ports {gt_txp_out0[3]}]
set_property PACKAGE_PIN AE59 [get_ports {gt_txn_out0[3]}]

#GTM QUAD 210
set_property PACKAGE_PIN AA67 [get_ports {gt_rxp_in1[0]}]
set_property PACKAGE_PIN AA68 [get_ports {gt_rxn_in1[0]}]
set_property PACKAGE_PIN AC61 [get_ports {gt_txp_out1[0]}]
set_property PACKAGE_PIN AC62 [get_ports {gt_txn_out1[0]}]
set_property PACKAGE_PIN AA64 [get_ports {gt_rxp_in1[1]}]
set_property PACKAGE_PIN AA65 [get_ports {gt_rxn_in1[1]}]
set_property PACKAGE_PIN AC58 [get_ports {gt_txp_out1[1]}]
set_property PACKAGE_PIN AC59 [get_ports {gt_txn_out1[1]}]
set_property PACKAGE_PIN W67 [get_ports {gt_rxp_in1[2]}]
set_property PACKAGE_PIN W68 [get_ports {gt_rxn_in1[2]}]
set_property PACKAGE_PIN AA61 [get_ports {gt_txp_out1[2]}]
set_property PACKAGE_PIN AA62 [get_ports {gt_txn_out1[2]}]
set_property PACKAGE_PIN W64 [get_ports {gt_rxp_in1[3]}]
set_property PACKAGE_PIN W65 [get_ports {gt_rxn_in1[3]}]
set_property PACKAGE_PIN AA58 [get_ports {gt_txp_out1[3]}]
set_property PACKAGE_PIN AA59 [get_ports {gt_txn_out1[3]}]
